version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/InfluxDB.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: iJEemO1Ww7XO4EXkCnS57+csNLUEc+VwRs/OQY/y+4cGGzatoy8UrzN4WrOC3y+f
  skip_symbols: true
  on:
    branch: dev
